log_folder: "logs"
log_level_console: "INFO"
log_level_file: "DEBUG"

database:
  url: "sqlite:///index.sqlite"
  echo: false

embedding_factory:
  batch_size: 1
  process_remote: false
  remote_host: "http://192.168.1.103"
  remote_port: 8000
  remote_endpoint: "/generate_embedding"
  timeout_seconds: 30

jira:
  api_key: ""
